### ISSUE TITLE
Progress bar with download rates?

### ISSUE THREAD

**Issue by dbrookeUAB** [r-lib/progress#108]
I'm trying to write a function that displays the speed at which I'm importing my single cell RNAseq datasets, but I'm having a hard time understanding how I'm supposed to integrate it with the progress bar. Can you give an example on how it would look with a function like `read.csv`?  Thanks!!

PS.. this package is easily my favorite R package.

**Comment by englianhu** [comment]
Some times the orogress bar stucking there, don't know wether algorithmic paused or system hanging there. Is it possible set the count unit for `progress_bar`? let say set as milisecond, microsecond, nanosecond and so ford...

- https://github.com/Lightning-AI/lightning/issues/9500

**Comment by gaborcsardi** [comment]
I suggest you try the cli package for progress bars, it supports rates out of the box, the articles have examples:
https://cli.r-lib.org/articles/progress.html
https://cli.r-lib.org/articles/progress-advanced.html
