### ISSUE TITLE
WISH: pb$tick(skip = TRUE) to tell ETA that we're skipping a step

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/progress#120]
AFAIU, the ETA ("estimate time to arrivial") is extrapolate from the currently elapsed time and the ratio (=steps/total) of progress this far and from that the ETA is estimated something like 'eta = (1-ratio)*elapsed'.

This is a decent estimator in many cases.  However, if we run a process that may skip certain steps, for instance due to cached results, then we're quickly get a biased estimate.  For instance, say we run 100 steps each of them takes 1 minute.  If the first 80 steps are already calculated and cached, then we'll reach ratio=0.80 momentarily, but the ETA will be extrapolated from that, resulting in a way too optimistic ETA.

To fix this, one could introduce a way to signal that we're skipping a step;

```r
> pb <- progress::progress_bar$new(total=100L, format=":percent in :elapsed :eta")
> for (kk 1:80) pb$tick(skip = TRUE)
> for (kk 81:100) pb$tick()
```

The ETA estimator could then adjust for by basically decreasing what it considers the 'total' number of steps; 'eta = (1-ratio_adjusted)*elapsed' where 'ratio_adjusted = (steps-skipped) / (total-skipped)'.

---

A generalization of this would be an `eta_len = len`, so that the above would be:

```r
> for (kk 1:80) pb$tick(eta_len = 0)
> for (kk 81:100) pb$tick()
```

This would allow us to use, say, `eta_len = 0.1` if the "cached" steps still takes 10% of the time that a regular step takes.  This approach would also allow developers to give ETAs on steps with fluctuating but predicable processing times.

**Comment by gaborcsardi** [comment]
We are focusing on the progress bars in the cli package, so I am going to close this now.
