### ISSUE TITLE
IS there a way to show every nth tick?

### ISSUE THREAD

**Issue by ScottSobel** [r-lib/progress#121]
Hello, I am enjoying your progress R package. I am running a process where each iteration is fast, but has hundreds of iterations until 100% complete. Is there a way to update the progress bar, say at every 50 ticks instead of updating at every tick? Thank you.

**Comment by gaborcsardi** [comment]
You can just update it every 50 ticks?

**Comment by ScottSobel** [comment]
Thanks, I suppose that is easy enough!
