### ISSUE TITLE
Progress to convergence not to iterations

### ISSUE THREAD

**Issue by ThomasDelSantoONeill** [r-lib/progress#125]
Hi, 

I was wondering if it was possible to add a progress bar for an iterative function in R where the progress is not meassured by the number of iterations in the loop but by proximity to a convergence threshold. If yes, could you provide a reproducible example? 

Thank you ever so much and hope to hear from you soon.

Tom

**Comment by gaborcsardi** [comment]
I believe this is possible with the cli package, which we prefer now for progress bars: 
https://cli.r-lib.org/reference/index.html#progress-bars
