### ISSUE TITLE
Showing progress bar in pane "background job" in RStudio

### ISSUE THREAD

**Issue by sebastian-gerdes** [r-lib/progress#127]
Dear all,

maybe I don't see the wood for the trees but I couldn't figure it out myself.

I have a long running for loop in a quarto document and I want to see the progress bar in RStudio when I render the document. How can this be done?

Any help is greatly appreciated!

Thanks and best greetings,
Sebastian

**Comment by gaborcsardi** [comment]
I suggest you take a look at the progress bars in the cli package, and if that doesn't solve your problem open an issue there. You can start here:
https://cli.r-lib.org/reference/index.html#progress-bars
