### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by pati-ni** [r-lib/progress#133]
If the loop is fast, tick() function is adding lots of overhead!

```
library(progress)
pb = progress_bar$new(total=100000)
system.time({for(i in 1:100000){pb$tick()}})

   user  system elapsed
 10.394   0.010  10.448
```

Therefore, this package is not very useful when the loop contains inexpensive operation. Please a faster path for these scenarios or warn users when the total is a big number.

**Comment by gaborcsardi** [comment]
Choose a different package then, e.g. https://cli.r-lib.org/reference/index.html#progress-bars
