### ISSUE TITLE
Positron support

### ISSUE THREAD

**Issue by lionel-** [r-lib/progress#135]
No output is emitted when running inside positron, see https://github.com/posit-dev/positron/issues/4501.

If I manually return `TRUE` from https://github.com/r-lib/progress/blob/07fb16db0dbe4dd910e5c6947eeba7018d2c4a78/R/utils.R#L52, I see the expected progress output.

cc @gaborcsardi

**Comment by gaborcsardi** [comment]
I see
```
> progress:::is_supported(stderr())
[1] FALSE
> progress:::is_supported(stdout())
[1] FALSE
```

**Comment by davisj95** [comment]
Does this mean that progress bar is not supported in positron? Will it be supported in the future?

**Comment by floswald** [comment]
yes, what's the status here? thanks

**Comment by lionel-** [comment]
You can install the dev version of progress to fix this:

```r
pak::pak("r-lib/progress")
```

@gaborcsardi Could we do a release to get this fix on CRAN?
