### ISSUE TITLE
Use of crayon and progress

### ISSUE THREAD

**Issue by richfitz** [r-lib/progress#32]
Because of the embedded ANSI codes, width calculation for progress bars that use crayon (or unicode characters probably) is off:

``` r
fmt <- sprintf("[%s] %s", crayon::red(":bar"), crayon::blue(":percent"))
pb <- progress::progress_bar$new(fmt,  total = 30, clear = FALSE, width = 80)
for (i in 1:30) {
  pb$tick()
  Sys.sleep(3 / 100)
}
message(paste0(rep("-", 80), collapse=""))
```

Not sure what the best fix is here.  If the ANSI codes are in the format, it could be unescaped and the difference between and apparent and true with calculated and added to width.  If custom tokens contain escapes they'd need treating on every tick.

**Comment by gaborcsardi** [comment]
Thanks! Indeed. I started writing up the string operations that work with ANSI strings: https://github.com/gaborcsardi/crayon/blob/master/R/string_operations.r

They are kinda slow, and I think I'll move them to another package at some point, so that progress does not have to depend on crayon.

**Comment by jimhester** [comment]
As of https://github.com/r-lib/progress/pull/52 progress uses the ANSI aware functions from crayon.
