### ISSUE TITLE
Custom token handling

### ISSUE THREAD

**Issue by richfitz** [r-lib/progress#40]
Two, probably related, issues with custom token handling here.  Can separate these into two issues if you'd like, in which case treat this as the first issue:

The full line is not correctly erased when a custom token does not
keep to a constant width.

```
tt <- seq(10, 0, by=-.5)
p <- progress::progress_bar$new("giving up in :remaining s", total=length(tt))
for (t in tt) {
  p$tick(tokens=list(remaining=t))
  Sys.sleep(.2)
}
```

which results in artefacts like

```
giving up in 9 s s
```

being printed.  I can work around this with `formatC` but it would be nice if the line erasing logic dealt with this directly.

The other issue is that the whitespace handling at the end of custom tokens seems to be dealt with differently than other tokens -- compare :remining(s) with :current(s)

```
tt <- seq(10, 0, by=-.5)
p <- progress::progress_bar$new("giving up in :remainings :currents",
                                total=length(tt))
for (t in tt) {
  p$tick(tokens=list(remaining=t))
  Sys.sleep(.1)
}
```

**Comment by gaborcsardi** [comment]
Thanks! 

I have started to rewrite progress in C and with better API: https://github.com/gaborcsardi/progress/tree/decorator

I'll handle these there.

**Comment by gaborcsardi** [comment]
Apparently both of these are fixed now.
