### ISSUE TITLE
:tick_rate:

### ISSUE THREAD

**Issue by hadley** [r-lib/progress#45]
It'd be nice to have a `tick_rate` parameter that gives the estimated number of ticks per second. Even better, you'd have some way to control the format of this value so you could add commas etc, when needed.

I'd like this for bigrquery where it's most natural to express the speed in the number of rows downloaded.

**Comment by louisaslett** [comment]
Agreed -- the rate parameter almost does what I want but unfortunately adds text treating the rate as a file download (i.e. B/s, MB/s, etc).  However, it would be nice to have a raw rate accessible with no "something/s" added: my use case is for MCMC simulations where it's nice to know the number of samples per second.

So being able to do a format string something like:

`"sampling [:bar] :rate samps/sec :percent eta: :eta"`

would be nice, but this renders `"... 104 B/s samps/sec  98% eta:  1m"`, so the `tick_rate` would do the job.
