### ISSUE TITLE
Allow setting of 'current' character in progress bar?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/progress#47]
We can specify the `complete` and `incomplete` characters in the progress bar constructor, but it would also be nice if we could specify the 'end' of the progress bar, so that we could draw e.g.

```
[=====>.....]
      ^ ~~ I want to be able to draw the right arrow here
```

**Comment by kevinushey** [comment]
This could also be useful for reporting an interrupted progress, e.g.

```
[=====!.....]
      ^ ~~ we got this far before interrupting the operation
```

**Comment by gaborcsardi** [comment]
Good idea.

**Comment by gaborcsardi** [comment]
I did not implement the interruption, though.  I  think on interruption you probably already have other messages, etc. to tell what has happened, changing this single character does not seem  that useful in addition.
