### ISSUE TITLE
Spinner progress visual not updating properly

### ISSUE THREAD

**Issue by EricGoldsmith** [r-lib/progress#57]
... when preceded by a call to `message()` if the `appendLF = FALSE` argument is used. Instead of the spinner repainting, it appends, like this:

```
Running job \:  1s:Running job |:  2s:Running job /:  2s:Running job -:  2s:Running job \:  3s:Running job |:  3s:Running job /:  3s:Running job -:  4s:Running job \:  4s:Running job |:  4s:Running job /:  4s:Running job -:  5s:Running job \:  5s:46.1 gigabytes processed ...
```

First noticed in the most recent version of [bigrquery](https://github.com/r-dbi/bigrquery/issues/192).

**Comment by gaborcsardi** [comment]
Hmmm, I don't see any `message` with `appendLD = FALSE` in `bigquery`...

**Comment by EricGoldsmith** [comment]
I was referring to the `message()` in base (i.e. `base::message("sample message", appendLF = FALSE)`). 

A common pattern in my code is to provide status of long queries like:
```
message("Querying XXX ... ", appendLF = FALSE)
# do the query
message("done.")
```

So that the output looks like:
`Querying XXX ... done.`

But, when using that pattern with the the spinner progress indicator (as `bigrquery` uses), you get the behavior above.

Not sure there's a feasible solution, but wanted to bring it to your attention.

**Comment by gaborcsardi** [comment]
Sorry, what I mean is that `bigquery` does not use `appendLF = FALSE`, so I am not sure how you can see this behavior with `bigquery`.

As for the issue, if a package starts to `message` or `print` or `cat`, etc. while the progress bar is active, there is not much I can do, I am afraid. `progress` has a `log` method to print to the screen and keep the progress bar proper, btw.

**Comment by EricGoldsmith** [comment]
The call to `message()` I was referring to above is in my code (i.e. not part of `bigrquery`), prior to calling `bigrquery`'s `query_exec()` function. Within` query_exec` is where the spinner progress indicator is called.

So, sounds like there's not a feasible solution except don't call `message()` with the a`appendLF = FALSE `option prior to something that uses the spinner progress indicator.

BTW, thanks for such a quick response!

Closing issue ...
