### ISSUE TITLE
Progress bar not printed on first tick/update

### ISSUE THREAD

**Issue by Enchufa2** [r-lib/progress#58]
According to the documentation,

> The progress bar is displayed after the first 'tick' command. This might not be desirable for long computations, because nothing is shown before the first tick. It is good practice to call 'tick(0)' at the beginning of the computation or download, which shows the progress bar immediately.

But actually it's not printed on first tick:

```r
tick <- progress::progress_bar$new()$tick
invisible(tick(0))
invisible(tick())
#> [=----------------------------------------------------------------------]   1%
```

Neither on first update:

```r
update <- progress::progress_bar$new()$update
invisible(update(0))
invisible(update(0.01))
#> [=----------------------------------------------------------------------]   1%
```

**Comment by gaborcsardi** [comment]
Yes, the docs are out of data, I'll update them in a sec. To force-show the progress bar, set `show_after` to zero and to a `tick(0)`:

```r
pb <- progress::progress_bar$new(show_after = 0)
invisible(pb$tick(0))
#> [-----------------------------------------------------------------------]   0%
```

**Comment by Enchufa2** [comment]
Then, I don't see the rationale behind `show_after` default value. I mean, if I want to use a progress bar, that's probably because I know that the process is long-lived. So I think that in general it would be better to have `show_after=0` as default. Moreover, if I'm explicitly calling `update(0)`, or `tick(0)`, it's because I want to show it right away. I think that this is against the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by gaborcsardi** [comment]
>  I mean, if I want to use a progress bar, that's probably because I know that the process is long-lived.

If you are writing generic code, then you often don't know if the process is long-lived or not.

> Moreover, if I'm explicitly calling update(0), or tick(0), it's because I want to show it right away.

There is no way to tell, if you are calling `tick(0)` to _show_ the progress bar, or from your regular loop.

Anyway, can you achieve the desired behavior with `show_after = 0` and a `tick()` call?

**Comment by Enchufa2** [comment]
Yes, it's ok, I can achieve it with `show_after=0`. My only concern is that I was expecting the default behaviour I found in the documentation (before reading the documentation, actually). Indeed, there are two use cases: 

1) You are using progressbar in an *ad hoc* way, because you have detected a long-lived process.
2) You are writing generic code, as you say.

My point is that, in 1), ideally, I wouldn't want to care about `show_after`, I just want good defaults to have it working with minimum pain. In 2), in contrast, the integration can be more thoughtful and I can think about the best value for `show_after`. But it's just my view. Maybe the use of progressbar is 2) in 99% of cases. That I don't know.
