### ISSUE TITLE
printing \r to stderr

### ISSUE THREAD

**Issue by kforner** [r-lib/progress#59]
Hi,
Reading this:
https://github.com/r-lib/progress/blob/6c98723b325227d35e37e38ee83a19e6d89d3f21/inst/include/RProgress.h#L256

I wonder: is the bug in R or in Rstudio console ? 
I kind of remember I got problems too with RcppProgress...

**Comment by gaborcsardi** [comment]
rstudio afair. It seems to be fixed now:
```
> cat("foo\rbar\n", file = stdout())
bar
> cat("foo\rbar\n", file = stderr())
bar
```

**Comment by kforner** [comment]
thanks.
