### ISSUE TITLE
purrr example in readme?

### ISSUE THREAD

**Issue by pgensler** [r-lib/progress#62]
It would be really helpful to have an example like the following in the readme for purrr:

```r
library(purrr)
library(dplyr)
# dummy list of 10 elements with random numbers
dummy_list <- rerun(10, runif(5))
# create the progress bar with a dplyr function. 
pb <- progress_estimated(length(dummy_list))
res <- dummy_list %>%
  map(~{
    # update the progress bar (tick()) and print progress (print())
    pb$tick()$print()
    Sys.sleep(0.5)
    sum(.x)
  })

```
Do you think this is a bit hacky code, as you are sleeping every .5 seconds?

**Comment by gaborcsardi** [comment]
Do you want to submit a PR?

**Comment by cderv** [comment]
I came up with this example in a discussion in tidyverse/purrr#149 thinking that everyone looking for progress bar in purrr would eventually find the issue with the example.
At the time, I was also wondering if this example belonged more to dplyr or purrr, in examples for map or a vignette.  
However, as there is this progress 📦 and the answer in the discussion mentionned some work on parallelism that could change the way it work, I said myself that the example in the issue was enough for the time, or that a post in community.rstudio.com would be enough to help show this example.

You think it should belong in the readme ?

**Comment by pgensler** [comment]
@gaborcsardi  I think this is a good example of how it can be used, but I just wanted to make sure it's not a hacky solution to put in a readme. @cderv the only objection I have is the `Sys.sleep call`, which to me, seems a bit unnecessary?

**Comment by cderv** [comment]
It was just an easy and dummy example to show how it works. the pause is here to let the progress bar appears on screen with small steps. 
We could work on another more realistic example. If you have an idea and wants to make a PR, feel free.
Personnaly, I am not sure this belongs into the readme of {purrr}. The example is made with {dplyr} but it could be made with {progress}, and maybe fits more in this repo README or vignettes, isn't it ?

**Comment by pgensler** [comment]
Yeah I have an example where I've tried to do some web scraping with purrr, which would be perfect for the progress bars. I'd be down to do a PR, and update this thread for your comments?

**Comment by cderv** [comment]
A web scraping example is a great use case. I still believe that for a readme example to show how it works a very simple example is enough. A more thorough use case of application could belong to a blog post or other documentation. However, if you believe it fits, go ahead with the PR with a link to this issue. If you want my comment, i'll be happy to do so in the opened PR.

**Comment by gaborcsardi** [comment]
Any example is good, it does not have to be realistic. You do the artificial example, you don't need to `sum()`, even just create a function that sleeps, call that in the `map()` and add a comment that the real computation goes there, this is just a placeholder. Thanks!

**Comment by gaborcsardi** [comment]
Please reopen if you want to submit an example.
