### ISSUE TITLE
progress bar in http requests?

### ISSUE THREAD

**Issue by sckott** [r-lib/progress#69]
curious if you've tried passing in a progress bar to `httr` using this package? trying it out, but can’t quite figure out how it needs to be set up. planning to have `crul` accept various progress bar inputs, like `httr::progress` or a `progress` pkg function

**Comment by gaborcsardi** [comment]
@sckott I don't think you can.

**Comment by gaborcsardi** [comment]
I think you can make it work with curl, because that just needs  a callback function. But AFAICT httr  implements its own progress bars.

**Comment by sckott** [comment]
okay, thanks
