### ISSUE TITLE
ERROR: installing package DESCRIPTION failed for package ‘progress’

### ISSUE THREAD

**Issue by rbenel** [r-lib/progress#70]
Hi, I am unable to update "progress" and there are many packages that depend on this successful update. 

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.28.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     lattice_0.20-35  assertthat_0.2.0 dplyr_0.7.6      grid_3.4.4      
 [6] plyr_1.8.4       R6_2.2.2         gtable_0.2.0     magrittr_1.5     scales_0.5.0    
[11] ggplot2_3.0.0    pillar_1.2.3     rlang_0.2.1      lazyeval_0.2.1   bindrcpp_0.2.2  
[16] Matrix_1.2-14    tools_3.4.4      glue_1.2.0       purrr_0.2.5      munsell_0.5.0   
[21] yaml_2.1.19      compiler_3.4.4   pkgconfig_2.0.1  colorspace_1.3-2 tidyselect_0.2.4
[26] bindr_0.1.1      tibble_1.4.2

**Comment by gaborcsardi** [comment]
You need  to  show what you did and what  error  you got.

**Comment by rbenel** [comment]
> install.packages("progress") Installing package into ‘/home/R/x86_64-pc-linux-gnu-library/3.4’ (as ‘lib’ is unspecified) trying URL 'https://cloud.r-project.org/src/contrib/progress_1.2.0.tar.gz' Content type 'application/x-gzip' length 27369 bytes (26 KB) ================================================== downloaded 26 KB  * installing *source* package ‘progress’ ... ** package ‘progress’ successfully unpacked and MD5 sums checked mv: cannot move '/home/yaellab/R/x86_64-pc-linux-gnu-library/3.4/progress' to '/home/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-progress/progress': Permission denied Warning in file.copy(f, instdir, TRUE) :   problem copying ./NAMESPACE to /home/R/x86_64-pc-linux-gnu-library/3.4/progress/NAMESPACE: Permission denied Warning in file.copy(f, instdir, TRUE) :   problem copying ./LICENSE to /home/R/x86_64-pc-linux-gnu-library/3.4/progress/LICENSE: Permission denied Warning in file(file, if (append) "a" else "w") :   cannot open file '/home/R/x86_64-pc-linux-gnu-library/3.4/progress/DESCRIPTION': Permission denied Error in file(file, if (append) "a" else "w") :    cannot open the connection ERROR: installing package DESCRIPTION failed for package ‘progress’ * removing ‘/home/R/x86_64-pc-linux-gnu-library/3.4/progress’ Warning in install.packages :   installation of package ‘progress’ had non-zero exit status  The downloaded source packages are in 	‘/tmp/RtmpNfBlnv/downloaded_packages’

**Comment by gaborcsardi** [comment]
lookslikeyoudon'thavewiteaccesstothedirectoryyouareinstallingto:package ‘progress’ successfully unpacked and MD5 sums checked mv: cannot move '/home/yaellab/R/x86_64-pc-linux-gnu-library/3.4/progress' to '/home/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-progress/progress': Permission denied Warning in file.copy(f, instdir, TRUE) : problem copying ./NAMESPACE to /home/R/x86_64-pc-linux-gnu-library/3.4/progress/NAMESPACE: Permission denied Warning in file.copy(f, instdir, TRUE) : problem copying ./LICENSE to /home/R/x86_64-pc-linux-gnu-library/3.4/progress/LICENSE: Permission denied Warning in file(file, if (append) "a" else "w") : cannot open file '/home/R/x86_64-pc-linux-gnu-library/3.4/progress/DESCRIPTION': Permission denied Error in file(file, if (append) "a" else "w") : cannot open the connection ERROR: installing package DESCRIPTION failed for package ‘progress’ * removing ‘/home/R/x86_64-pc-linux-gnu-library/3.4/progress’ Warning in install.packages : installation of package ‘progress’ had non-zero exit status The downloaded source packages are in ‘/tmp/RtmpNfBlnv/downloaded_packages’

**Comment by rbenel** [comment]
Thank You :)

**Comment by gaborcsardi** [comment]
Maybe you just need  to remove that lock file,  that  might  be a leftover  from a broken installation: `/home/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-progress`
