### ISSUE TITLE
Print total duration on completion

### ISSUE THREAD

**Issue by jarauh** [r-lib/progress#73]
It would be good if the progress bar could report the total duration.  At least, it could make the starting time available publicly.  Or there could be a method that provides the running time so far (and the total duration on completion).

**Comment by scottkosty** [comment]
> Or there could be a method that provides the running time so far (and the total duration on completion).

Indeed, this would be helpful when combined with `clear = FALSE`. During the actual computation, I want to know `:eta`. But after the computation is done, I would like to know how long it took. I prefer not to use *both* `:elapsed` and `:eta`.

**Comment by gaborcsardi** [comment]
I believe this is possible with the cli package, which we prefer now for progress bars: https://cli.r-lib.org/reference/index.html#progress-bars

**Comment by jarauh** [comment]
Thanks for the pointer to cli, @gaborcsardi. Just for curiosity, who is "we" (in "we prefer" cli)?
Do you consider `progress` to be deprecated?

**Comment by gaborcsardi** [comment]
"we" is the r-lib/tidyverse team. progress is de facto superseded by cli, it will be formally superseded soon. It is not going away, and we'll fix serious bugs, but won't add new features.

**Comment by jarauh** [comment]
Thank you, good to know.
