### ISSUE TITLE
Support for RKWard

### ISSUE THREAD

**Issue by devillemereuil** [r-lib/progress#74]
It seems `progress` is suppressing printing the progress bar from within [RKWard](https://rkward.kde.org/), which an R IDE from KDE, see [here for more details](https://www.mail-archive.com/rkward-devel@kde.org/msg01169.html).

Would there be a way to enable `progress` from within RKWard's console? I'm happy to test any patch. Note that RKWard is available for Windows and Mac OS X and not restricted to GNU/Linux, if this makes it simpler to make a patch for it.

Thanks for this awesome package!

**Comment by devillemereuil** [comment]
Note that using force = TRUE make the progress bar appear without issue.

**Comment by gaborcsardi** [comment]
How do you detect RKWard? PRs are welcome!

**Comment by devillemereuil** [comment]
The devs gave me a way, I'll try to submit a PR soon(ish). I guess I need to create an is_rkward() and an rkward_stdx() functions and add the latter to is_supported()? Or am I oversimplifying this?

**Comment by gaborcsardi** [comment]
Yeah, sounds good!

**Comment by devillemereuil** [comment]
Sorry, I forgot to include the bug number in the PR supposed to close this bug... So for reference, [PR76](https://github.com/r-lib/progress/pull/76) is linked to this bug.

**Comment by gaborcsardi** [comment]
Closed by #76.
