### ISSUE TITLE
Ability to update the message?

### ISSUE THREAD

**Issue by jennybc** [r-lib/progress#82]
Related to my readxl usage of a common progress bar (spinner, actually) for a couple distinct steps. Could we ever update the `format` of an existing progress bar? Or maybe in the simple case of a spinner?

**Comment by jsta** [comment]
I was looking to do this. In my case, I knew the distinct steps ahead of time so I was able to use their number,  inflate the number of ticks, and update the message:

MWE at https://gist.github.com/jsta/5061e0d1b4511a0d4570ada39c143110

**Comment by gaborcsardi** [comment]
You can do this with cli progress bars, so I am going to close this now.
