### ISSUE TITLE
Central support for a `progress`argument in user-facing functions of client packages

### ISSUE THREAD

**Issue by jennybc** [r-lib/progress#83]
Summarizing a Slack discussion: progress should provide more centralized support for client packages that expose a logical argument that controls whether progress should be displayed.

We need a helper we can call as the default strategy and it will have a lot in common with this function I've nicked from readr:

``` r
show_progress <- function() {
  isTRUE(getOption("readr.show_progress")) && # user disables progress bar
  interactive() && # an interactive session
  !isTRUE(getOption("rstudio.notebook.executing")) && # Not running in an RStudio notebook chunk
  !isTRUE(getOption("knitr.in.progress")) # Not actively knitting a document
}
```

**Comment by gaborcsardi** [comment]
As we are focusing on the cli package now for progress bars, I am going to close this.
