### ISSUE TITLE
Should progress use a custom width option like cli?

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/progress#87]
This is a kind of reboot of this issue I opened up on `cli`: https://github.com/r-lib/cli/issues/56

My symptoms with `progress` are similar to those I describe there, i.e. I have bulk text blowing up my REPL because the progress bars are 10000 characters long. I use this setting because it makes printing of dataframes and tibbles nicer (in ESS).

So right now I have this in my `.Rprofile`:

```
options(
  cli.width = 80,
  width = 10000
)
```
It would be nice if I could limit the progress bars to 80 chars.

**Comment by jimhester** [comment]
If you want wider tibbles there is already a custom option for that, `tibble.width`. I don't if there is a great alternative for regular data frames, but you could always define a custom print method if you want. From the documentation `options("width")` is clearly explicitly meant to be the width of the terminal window, so IMHO I don't think it would be necessary to add an additional option.

**Comment by gaborcsardi** [comment]
@jimhester this is all true, but it also makes sense to have an option for progress. I think we can just use the same `cli.width` option.

**Comment by gaborcsardi** [comment]
As we are focusing on cli now for progress bars, I am going to close this now.
