### ISSUE TITLE
More convenient use of progress in for loops

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/progress#90]
I played around with [this question](https://stackoverflow.com/questions/7349570/wrapper-to-for-loops-with-progress-bar) on SO. 

My solution that I packaged [there](https://github.com/moodymudskipper/pbfor)  wraps around *progress* and allows one to use either of the following syntaxes : 

```
pb_for()
for (i in 1:10) {
  # DO SOMETHING
}

pb <- progress_bar$new(format = "Something: [:bar] :percent :elapsed")
pb  -> for (i in 1:10) {
  # DO SOMETHING
}
```

It uses some quirks of the R language but it offers an intuitive interface and avoids the current issue of having to type "2 things".

You can find more by following either link above. The code might be too weird for this package but if you think it might have a place here it's yours to take and tweak.

**Comment by gaborcsardi** [comment]
In the similar spirit, see this in cli: https://cli.r-lib.org/reference/cli_progress_along.html

We are focusing on cli now, so I am going to close this issue.
