### ISSUE TITLE
Bad printout in RStudio Server

### ISSUE THREAD

**Issue by eliocamp** [r-lib/progress#96]
I'm starting to use Rstudio server and found that progress bars fail to print correctly. This is what I'm getting:

```r
pbar_test <- function() {
  pb <- progress::progress_bar$new(total = 100)
  
  for (i in 1:100) {
    Sys.sleep(0.1)
    pb$tick()
  }
}

pbar_test()
```

![pbar_server](https://user-images.githubusercontent.com/8617595/63461982-38af5600-c430-11e9-8744-d45d2a774bf7.gif)

As a sanity check, the same testing function works properly on my local instance

![pbar_local](https://user-images.githubusercontent.com/8617595/63462075-7b712e00-c430-11e9-9214-5fcd26703ad3.gif)

Rstudio Server version is 1.0.153 if that helps (I don't admin have access to update it, unfortunately :( )

**Comment by jxu** [comment]
My guess is that this is an issue with Rstudio carriage return. What OS are you on? I have this issue on windows

**Comment by jxu** [comment]
I was on Version 1.0.153 for Windows and it was broken. I updated to 1.3.1056 and it is fixed now.
